### ISSUE TITLE
iPad Air 4.1 Unsupported model error

### ISSUE THREAD

**Issue by velejaj** [MatthewPierson/Vieux#119] opened 2020-04-06 00:25 UTC
Hi,
I have iPad Air 4.1, MacBook Pro on macOs Catalina 10.15.4
I'm trying to downgrade from 12.4 to 10.3.3. and I get same error all the time. 

![Screenshot 2020-04-06 at 02 13 18](https://user-images.githubusercontent.com/63214669/78513497-6e7d3100-77ac-11ea-9cc2-eaa9613a1446.png)

I tried with ./vieux -i and with python3 vieux -i, I get sam error.

![Screenshot 2020-04-06 at 02 17 11](https://user-images.githubusercontent.com/63214669/78513596-1abf1780-77ad-11ea-86a8-fa724d455ab5.png)

When I type ./vieux -p I get this

![Screenshot 2020-04-06 at 02 21 40](https://user-images.githubusercontent.com/63214669/78513639-75f10a00-77ad-11ea-92ff-d343befe3114.png)

I tried to download IPSW file few times and it didn't help.

Any suggestions?

Thanks

**Comment by thanhmom123** [comment] 2020-04-06 10:56
i have a same question
i use ipad air 4.2 with mac os 10.15.4
when i type ' python3 vieux -i ' its not working 
ERROR: Unsupported model...

**Comment by velejaj** [comment] 2020-04-06 23:35
I finaly did my downgrade on my old white unibody MacBook with High Sierra on it.
Only vieux worked.
So, the error is probably because of Catalina.

**Comment by FrolovNikita** [comment] 2020-04-14 16:28
@velejaj @thanhmom123 Hey! I had the same problem "ERROR: Unsupported model...". This comment helped me today to downgrade my iPad mini 2 4,4 iOS 12.4.4 to 10.3.3. [Link: "Seems that is a problem with code signing executable."](https://github.com/MatthewPierson/Vieux/issues/126#issuecomment-612641213)

**Comment by MatthewPierson** [comment] 2020-04-15 00:03
@velejaj If the issue is no longer a problem please close this issue! For others running into this same issue either try what @FrolovNikita linked or use the other fix shown in the [README](https://github.com/MatthewPierson/Vieux#macos-catalina-security-issues)

**Closed** 2020-04-15 00:08 UTC
